
global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#dmitry_lyutenko'
