---
# tasks file for 

- name: install additional packages
  apt:
    name: ["apt-transport-https","ca-certificates","curl","gnupg-agent","software-properties-common"]
    update_cache: yes

- name: add key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    filename: docker

- name: Install Docker
  apt:
    name: docker-ce
    state: present
