version: '3.3'
services:
  post_db:
    image: mongo:latest
    container_name: ${post_db_name}
    volumes:
      - ${db_volume}:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:${UI_VERSION}
    container_name: ${ui_name}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - ${EXP_PORT}:9292/tcp
    networks:
      - ${front_net}
    logging:
      driver: "fluentd"
      options: 
        fluentd-address: localhost:24224
        tag: service.ui
  post:
    image: ${USERNAME}/post:${POST_VERSION}
    container_name: ${post_name}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    logging:
      driver: "fluentd"
      options: 
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      - ${back_net}
      - ${front_net}
  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    container_name: ${comment_name}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - ${back_net}
      - ${front_net}
    logging:
      driver: "fluentd"
      options: 
        fluentd-address: localhost:24224
        tag: service.comment

volumes:
  post_db:


networks:
  front_net:
  back_net:
