apiVersion: v1
kind: PersistentVolume
metadata:
  name: reddit-mongddb-disk
spec:
  capacity: 
    storage: 25Gi
  accessModes:
    - ReadwriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: "reddit-mongodb-disk"
    fsType: ext4
