---
- name: Install docker module if needed
  raw: test -n "$(pip show dockers)" || (apt-get -y install python-pip && pip install docker)
  changed_when: False

  
- name: Pull image
  docker_image:
    name: "{{ docker_image }}"
    pull: true

- name: Run container
  raw: docker run -d -p 9292:9292 --name reddit {{ docker_image }}
