version: '3.3'
services:
  ui:
    command: puma --debug -w 2
    volumes:
      - ./srv/reddit/ui:/app
    depends_on:
      - update
  post:
  comment:
    command: sh -c "bundle install && puma --debug -w2"
    volumes:
      - ./srv/reddit/comment:/app
    depends_on:
      - update

  update:
    build: ./update
    image: ${USERNAME}/update:1.0
    volumes:
      - ./srv:/app


volumes:
  post_db:
  app_volume:


networks:
  front_net:
  back_net:
